### ISSUE TITLE
New location repo

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/location#1]
I created this thinking that @almereyda might want to set up camp here at some point and work on LOD based on TransforMap.  (If not, that's OK too.  Or if somewhere else, that's totally cool.)  But it would be great to be able to have a good vocab for location that could be linked to agent, resource, and probably other stuff!

**Comment by ahdinosaur** [comment]
:+1:. related: https://github.com/valueflows/valueflows/issues/69

**Comment by almereyda** [comment]
Here I am @fosterlynn, finally came from what is mentioned below. I've also recognized https://discourse.transformap.co/t/valueflows-and-transformap-coordination/760 today, why I will try to circle around these issues within the next days. Also I am about to write some kind of API for TransforMap within the next month, if @ahdinosaur would like to counsel a bit.

**Comment by fosterlynn** [comment]
@almereyda nice!  Will look forward to it.  (BTW, I'm not trying to get you to work in this space, it doesn't matter one bit to me.  If location / POI should be a separate vocab, that's totally fine.  Just wanting us to coordinate it so they fit together!)
